### ISSUE TITLE
Need help ? 

### ISSUE THREAD

**Issue by jalotra** [HackerPen/tech-interview-questions#1]
This will have leetcode type questions ?

**Comment by marshallshen** [comment]
@jalotra Yup! Some leetcode questions will be added :)

**Comment by jalotra** [comment]
Okay, I would like to help add some questions, checkout binarysearch.com, they have some great, easy worded questions as well.

**Comment by marshallshen** [comment]
Hi @jalotra , I pushed up the basic repo structure, and you can follow the README on how to add questions.
Also, you don't have questions to add, check out #2 for some questions to add :)

Close this issue now, thanks!
